// Generated by gencpp from file projeto_02/CameraResRequest.msg
// DO NOT EDIT!


#ifndef PROJETO_02_MESSAGE_CAMERARESREQUEST_H
#define PROJETO_02_MESSAGE_CAMERARESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace projeto_02
{
template <class ContainerAllocator>
struct CameraResRequest_
{
  typedef CameraResRequest_<ContainerAllocator> Type;

  CameraResRequest_()
    {
    }
  CameraResRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::projeto_02::CameraResRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::projeto_02::CameraResRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CameraResRequest_

typedef ::projeto_02::CameraResRequest_<std::allocator<void> > CameraResRequest;

typedef boost::shared_ptr< ::projeto_02::CameraResRequest > CameraResRequestPtr;
typedef boost::shared_ptr< ::projeto_02::CameraResRequest const> CameraResRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::projeto_02::CameraResRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::projeto_02::CameraResRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace projeto_02

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::projeto_02::CameraResRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::projeto_02::CameraResRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::projeto_02::CameraResRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::projeto_02::CameraResRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::projeto_02::CameraResRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::projeto_02::CameraResRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::projeto_02::CameraResRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::projeto_02::CameraResRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::projeto_02::CameraResRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "projeto_02/CameraResRequest";
  }

  static const char* value(const ::projeto_02::CameraResRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::projeto_02::CameraResRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::projeto_02::CameraResRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::projeto_02::CameraResRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraResRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::projeto_02::CameraResRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::projeto_02::CameraResRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PROJETO_02_MESSAGE_CAMERARESREQUEST_H
