// Generated by gencpp from file projeto_02/CameraResResponse.msg
// DO NOT EDIT!


#ifndef PROJETO_02_MESSAGE_CAMERARESRESPONSE_H
#define PROJETO_02_MESSAGE_CAMERARESRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace projeto_02
{
template <class ContainerAllocator>
struct CameraResResponse_
{
  typedef CameraResResponse_<ContainerAllocator> Type;

  CameraResResponse_()
    : res(0)  {
    }
  CameraResResponse_(const ContainerAllocator& _alloc)
    : res(0)  {
  (void)_alloc;
    }



   typedef int32_t _res_type;
  _res_type res;





  typedef boost::shared_ptr< ::projeto_02::CameraResResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::projeto_02::CameraResResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CameraResResponse_

typedef ::projeto_02::CameraResResponse_<std::allocator<void> > CameraResResponse;

typedef boost::shared_ptr< ::projeto_02::CameraResResponse > CameraResResponsePtr;
typedef boost::shared_ptr< ::projeto_02::CameraResResponse const> CameraResResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::projeto_02::CameraResResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::projeto_02::CameraResResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::projeto_02::CameraResResponse_<ContainerAllocator1> & lhs, const ::projeto_02::CameraResResponse_<ContainerAllocator2> & rhs)
{
  return lhs.res == rhs.res;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::projeto_02::CameraResResponse_<ContainerAllocator1> & lhs, const ::projeto_02::CameraResResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace projeto_02

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::projeto_02::CameraResResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::projeto_02::CameraResResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::projeto_02::CameraResResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::projeto_02::CameraResResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::projeto_02::CameraResResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::projeto_02::CameraResResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::projeto_02::CameraResResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca16cfbd5443ad97f6cc7ffd6bb67292";
  }

  static const char* value(const ::projeto_02::CameraResResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca16cfbd5443ad97ULL;
  static const uint64_t static_value2 = 0xf6cc7ffd6bb67292ULL;
};

template<class ContainerAllocator>
struct DataType< ::projeto_02::CameraResResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "projeto_02/CameraResResponse";
  }

  static const char* value(const ::projeto_02::CameraResResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::projeto_02::CameraResResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 res\n"
;
  }

  static const char* value(const ::projeto_02::CameraResResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::projeto_02::CameraResResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraResResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::projeto_02::CameraResResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::projeto_02::CameraResResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<int32_t>::stream(s, indent + "  ", v.res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJETO_02_MESSAGE_CAMERARESRESPONSE_H
