// Generated by gencpp from file projeto_02/CameraRes.msg
// DO NOT EDIT!


#ifndef PROJETO_02_MESSAGE_CAMERARES_H
#define PROJETO_02_MESSAGE_CAMERARES_H

#include <ros/service_traits.h>


#include <projeto_02/CameraResRequest.h>
#include <projeto_02/CameraResResponse.h>


namespace projeto_02
{

struct CameraRes
{

typedef CameraResRequest Request;
typedef CameraResResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraRes
} // namespace projeto_02


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::projeto_02::CameraRes > {
  static const char* value()
  {
    return "ca16cfbd5443ad97f6cc7ffd6bb67292";
  }

  static const char* value(const ::projeto_02::CameraRes&) { return value(); }
};

template<>
struct DataType< ::projeto_02::CameraRes > {
  static const char* value()
  {
    return "projeto_02/CameraRes";
  }

  static const char* value(const ::projeto_02::CameraRes&) { return value(); }
};


// service_traits::MD5Sum< ::projeto_02::CameraResRequest> should match
// service_traits::MD5Sum< ::projeto_02::CameraRes >
template<>
struct MD5Sum< ::projeto_02::CameraResRequest>
{
  static const char* value()
  {
    return MD5Sum< ::projeto_02::CameraRes >::value();
  }
  static const char* value(const ::projeto_02::CameraResRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::projeto_02::CameraResRequest> should match
// service_traits::DataType< ::projeto_02::CameraRes >
template<>
struct DataType< ::projeto_02::CameraResRequest>
{
  static const char* value()
  {
    return DataType< ::projeto_02::CameraRes >::value();
  }
  static const char* value(const ::projeto_02::CameraResRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::projeto_02::CameraResResponse> should match
// service_traits::MD5Sum< ::projeto_02::CameraRes >
template<>
struct MD5Sum< ::projeto_02::CameraResResponse>
{
  static const char* value()
  {
    return MD5Sum< ::projeto_02::CameraRes >::value();
  }
  static const char* value(const ::projeto_02::CameraResResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::projeto_02::CameraResResponse> should match
// service_traits::DataType< ::projeto_02::CameraRes >
template<>
struct DataType< ::projeto_02::CameraResResponse>
{
  static const char* value()
  {
    return DataType< ::projeto_02::CameraRes >::value();
  }
  static const char* value(const ::projeto_02::CameraResResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROJETO_02_MESSAGE_CAMERARES_H
